In [3]:
import numpy as np

In [6]:
arr = np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [7]:
list_of_lists = [[1,2,3],[4,5,6],[7,8,9]]
list_of_lists

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
mtrx = np.array(list_of_lists)
mtrx

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
np.arange(5,20)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [11]:
np.arange(18)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])

In [12]:
np.arange(1,20,5)

array([ 1,  6, 11, 16])

In [13]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [14]:
np.zeros(5,int)

array([0, 0, 0, 0, 0])

In [15]:
np.zeros((2,3),dtype = int)

array([[0, 0, 0],
       [0, 0, 0]])